<?php

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 * @var $sizeGuideVm \Aus\Task8\ViewModel\StockLevel
 */
?>
<?php
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

if ($_product->getTypeId() !== \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE) {
    return;
}
$stockLevelVm = $block->getData('stock_level_vm');
$stockLevel = $stockLevelVm->getStockLevelByIdentifier($_product->getId());
?>
<?php if ($_product->isAvailable()) :?>
    <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <span><?= $block->escapeHtml(__('In stock')) ?></span>
    </div>
<?php else :?>
    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
    </div>
<?php endif; ?>
<div class="product-stock-level ">
        <strong class="type"><?= $stockLevel->getQty(); ?></strong>
</div>
