<?php

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 * @var $sizeGuideVm \Aus\Task8\ViewModel\StockLevel
 */
?>
<?php
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$stockLevelVm = $block->getData('stock_level_vm');
$stockLevel = $stockLevelVm->getStockLevelByIdentifier($_product->getId());
?>
<div class="product-stock-level ">
        <strong class="type"><?= $stockLevel->getQty(); ?></strong>
</div>
